"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-03 12:37:38.175298
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this database revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ACCEPTED_VALUE",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    op.create_table(
        "ANNOTATION_STANDARD",
        sa.Column("standard_id", sa.String(length=50), nullable=False),
        sa.Column("standard_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("regex", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("standard_id"),
    )
    op.create_table(
        "ANNOTATION_VALUE",
        sa.Column("value_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("annotation_value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("value_id"),
        sa.UniqueConstraint("annotation_value"),
    )
    op.create_table(
        "CONFLICT",
        sa.Column("conflict_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("conflict_id"),
    )
    op.create_table(
        "COUNTRY",
        sa.Column("country_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("country_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("country_id"),
    )
    op.create_index(
        op.f("ix_COUNTRY_country_code"), "COUNTRY", ["country_code"], unique=True
    )
    op.create_index(
        op.f("ix_COUNTRY_country_name"), "COUNTRY", ["country_name"], unique=True
    )
    op.create_table(
        "ELAN_FILE_MEDIA",
        sa.Column("media_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_url", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("relative_media_url", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("media_id"),
    )
    op.create_table(
        "FILE_TYPE",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("extension", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("extension"),
    )
    op.create_table(
        "INSTANCE",
        sa.Column("instance_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("instance_name", sa.String(length=100), nullable=False),
        sa.Column("institution_name", sa.String(length=100), nullable=False),
        sa.Column("contact_email", sa.String(length=100), nullable=False),
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("default_language", sa.String(length=10), nullable=False),
        sa.Column(
            "max_file_size_mb", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("max_users", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("instance_id"),
    )
    op.create_table(
        "OUTBOX_EVENT",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_OUTBOX_EVENT_aggregate_id"),
        "OUTBOX_EVENT",
        ["aggregate_id"],
        unique=False,
    )
    op.create_table(
        "CITY",
        sa.Column("city_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("city_name", sa.String(length=100), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("region_state", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["COUNTRY.country_id"],
        ),
        sa.PrimaryKeyConstraint("city_id"),
    )
    op.create_index(
        "idx_country_city", "CITY", ["country_id", "city_name"], unique=False
    )
    op.create_index(op.f("ix_CITY_city_name"), "CITY", ["city_name"], unique=False)
    op.create_table(
        "COMPONENT_TEMPLATE",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("regex", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_type_id"],
            ["FILE_TYPE.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "file_type_id", "name", "regex", "description", name="uq_component_template"
        ),
    )
    op.create_table(
        "PROJECT",
        sa.Column("project_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("project_path", sa.String(length=512), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instance_id"], ["INSTANCE.instance_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id"),
        sa.UniqueConstraint("project_path"),
    )
    op.create_index(
        op.f("ix_PROJECT_deleted_at"), "PROJECT", ["deleted_at"], unique=False
    )
    op.create_table(
        "ADDRESS",
        sa.Column("address_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("street_number", sa.String(length=100), nullable=True),
        sa.Column("street_name", sa.String(length=100), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("address_line_2", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["CITY.city_id"],
        ),
        sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_index(op.f("ix_ADDRESS_city_id"), "ADDRESS", ["city_id"], unique=False)
    op.create_index(
        op.f("ix_ADDRESS_postal_code"), "ADDRESS", ["postal_code"], unique=False
    )
    op.create_table(
        "COMPONENT_ACCEPTED_VALUE",
        sa.Column("component_template_id", sa.Integer(), nullable=False),
        sa.Column("accepted_value_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accepted_value_id"], ["ACCEPTED_VALUE.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["component_template_id"], ["COMPONENT_TEMPLATE.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("component_template_id", "accepted_value_id"),
    )
    op.create_table(
        "PROJECT_ANNOT_STANDARD",
        sa.Column("standard_id", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["PROJECT.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["standard_id"],
            ["ANNOTATION_STANDARD.standard_id"],
        ),
        sa.PrimaryKeyConstraint("standard_id", "project_id"),
    )
    op.create_table(
        "PROJECT_FILE_TYPE",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("file_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_type_id"],
            ["FILE_TYPE.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["PROJECT.project_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_project_filetype_name"),
    )
    op.create_table(
        "TIER_SECTION",
        sa.Column("tier_section_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("section_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["PROJECT.project_id"],
        ),
        sa.PrimaryKeyConstraint("tier_section_id"),
    )
    op.create_index(
        op.f("ix_TIER_SECTION_tier_section_id"),
        "TIER_SECTION",
        ["tier_section_id"],
        unique=False,
    )
    op.create_table(
        "PROJECT_LOCATION_FILE_TYPE",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("project_file_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_file_type_id"], ["PROJECT_FILE_TYPE.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["PROJECT.project_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "location_id",
            "project_file_type_id",
            name="uq_project_location_filetype",
        ),
    )
    op.create_table(
        "PROJECT_NAMING_STANDARD",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("project_file_type_id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_file_type_id"],
            ["PROJECT_FILE_TYPE.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["PROJECT.project_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "project_file_type_id",
            "name",
            name="uq_project_filetype_standard",
        ),
    )
    op.create_table(
        "USER",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("affiliation", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("activation_code", sa.String(length=100), nullable=False),
        sa.Column("is_verified_account", sa.Boolean(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "PUBLIC", name="userrole"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"], ["ADDRESS.address_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"], ["INSTANCE.instance_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_USER_address_id"), "USER", ["address_id"], unique=False)
    op.create_index(op.f("ix_USER_affiliation"), "USER", ["affiliation"], unique=False)
    op.create_index(op.f("ix_USER_department"), "USER", ["department"], unique=False)
    op.create_index(op.f("ix_USER_email"), "USER", ["email"], unique=True)
    op.create_index(op.f("ix_USER_is_active"), "USER", ["is_active"], unique=False)
    op.create_index(op.f("ix_USER_instance_id"), "USER", ["instance_id"], unique=False)
    op.create_index(
        op.f("ix_USER_is_verified_account"),
        "USER",
        ["is_verified_account"],
        unique=False,
    )
    op.create_index(op.f("ix_USER_last_login"), "USER", ["last_login"], unique=False)
    op.create_index(op.f("ix_USER_role"), "USER", ["role"], unique=False)
    op.create_index(op.f("ix_USER_username"), "USER", ["username"], unique=True)
    op.create_table(
        "AUDIT_EVENT",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["USER.user_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["PROJECT.project_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_AUDIT_EVENT_action"), "AUDIT_EVENT", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_AUDIT_EVENT_occurred_at"), "AUDIT_EVENT", ["occurred_at"], unique=False
    )
    op.create_table(
        "COMMENT",
        sa.Column("comment_id", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "PROJECT",
                "ELAN_FILE",
                "CONFLICT",
                "TIER",
                "ANNOTATION",
                name="commenttargettype",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parent_comment_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_comment_id"], ["COMMENT.comment_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["USER.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_table(
        "EFFECTIVE_NAMING_STANDARD",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("project_file_type_id", sa.Integer(), nullable=False),
        sa.Column("naming_standard_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["naming_standard_id"], ["PROJECT_NAMING_STANDARD.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_file_type_id"], ["PROJECT_FILE_TYPE.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["PROJECT.project_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "project_file_type_id",
            "location_id",
            name="uq_project_filetype_location",
        ),
    )
    op.create_table(
        "FILE_CONTENT",
        sa.Column("content_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["USER.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("content_id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "INVITATION",
        sa.Column("invitation_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_permission", sa.String(length=20), nullable=False),
        sa.Column("hashed_code", sa.String(length=60), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACCEPTED", "REJECTED", "EXPIRED", name="invitationstatus"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("responded_at", sa.DateTime(), nullable=True),
        sa.Column("sender", sa.Integer(), nullable=False),
        sa.Column("receiver", sa.Integer(), nullable=True),
        sa.Column("receiver_email", sa.String(length=100), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["PROJECT.project_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["receiver"],
            ["USER.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender"],
            ["USER.user_id"],
        ),
        sa.PrimaryKeyConstraint("invitation_id"),
    )
    op.create_table(
        "NOTIFICATION",
        sa.Column("notification_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["USER.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    op.create_index(
        op.f("ix_NOTIFICATION_created_at"), "NOTIFICATION", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_NOTIFICATION_is_read"), "NOTIFICATION", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_NOTIFICATION_user_id"), "NOTIFICATION", ["user_id"], unique=False
    )
    op.create_table(
        "NOTIFICATION_PREFERENCE",
        sa.Column("preference_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["USER.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("preference_id"),
    )
    op.create_index(
        op.f("ix_NOTIFICATION_PREFERENCE_user_id"),
        "NOTIFICATION_PREFERENCE",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "PENDING_UPLOAD",
        sa.Column("upload_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "upload_type",
            sa.Enum(
                "ANNOTATION_OVERLAP",
                "TIER_MISMATCH",
                "VALUE_DIFFERENCE",
                "STRUCTURAL",
                "OTHER",
                "PENDING_UPLOAD",
                "UPLOAD_NEW_FILES_ONLY",
                "UPLOAD_WITH_MODIFICATIONS",
                "UPLOAD_WITH_DELETIONS",
                "UPLOAD_MIXED_CHANGES",
                name="type",
            ),
            nullable=False,
        ),
        sa.Column("upload_description", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_ADMIN_APPROVAL",
                "READY_TO_MERGE",
                "NEEDS_RESOLUTION",
                "BEING_REVIEWED",
                "RESOLVED",
                "DISMISSED",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("branch_name", sa.String(), nullable=True),
        sa.Column("git_details", sa.JSON(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["PROJECT.project_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["USER.user_id"],
        ),
        sa.PrimaryKeyConstraint("upload_id"),
    )
    op.create_table(
        "STANDARD_COMPONENT",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("naming_standard_id", sa.Integer(), nullable=False),
        sa.Column("component_template_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_template_id"], ["COMPONENT_TEMPLATE.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["naming_standard_id"], ["PROJECT_NAMING_STANDARD.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "USER_TO_PROJECT",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("permission", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["PROJECT.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.user_id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id"),
    )
    op.create_table(
        "USER_WORK_ON_CONFLICT",
        sa.Column("conflict_id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conflict_id"],
            ["CONFLICT.conflict_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.user_id"],
        ),
        sa.PrimaryKeyConstraint("conflict_id", "user_id"),
    )
    op.create_table(
        "COMMENT_CONFLICT",
        sa.Column("comment_id", sa.String(length=50), nullable=False),
        sa.Column("conflict_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["COMMENT.comment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["conflict_id"],
            ["CONFLICT.conflict_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_table(
        "COMMENT_PROJECT",
        sa.Column("comment_id", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["COMMENT.comment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["PROJECT.project_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_table(
        "ELAN_FILE",
        sa.Column("elan_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"], ["FILE_CONTENT.content_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["PROJECT.project_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("elan_id"),
        sa.UniqueConstraint("content_id", "project_id", name="uq_content_project"),
    )
    op.create_table(
        "COMMENT_ELAN_FILE",
        sa.Column("comment_id", sa.String(length=50), nullable=False),
        sa.Column("elan_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["COMMENT.comment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["elan_id"],
            ["ELAN_FILE.elan_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_table(
        "CONFLICT_OF_ELAN_FILE",
        sa.Column("conflict_id", sa.String(length=50), nullable=False),
        sa.Column("elan_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conflict_id"],
            ["CONFLICT.conflict_id"],
        ),
        sa.ForeignKeyConstraint(
            ["elan_id"],
            ["ELAN_FILE.elan_id"],
        ),
        sa.PrimaryKeyConstraint("conflict_id", "elan_id"),
    )
    op.create_table(
        "EAF_REVISION",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("elan_id", sa.Integer(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("raw_xml", sa.LargeBinary(), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=True),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(sha256) = 64", name="ck_eaf_revision_sha256"),
        sa.CheckConstraint("revision_number > 0", name="ck_eaf_revision_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["USER.user_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["elan_id"], ["ELAN_FILE.elan_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("revision_id"),
        sa.UniqueConstraint(
            "elan_id", "revision_number", name="uq_eaf_revision_number"
        ),
        sa.UniqueConstraint("elan_id", "sha256", name="uq_eaf_revision_content"),
    )
    op.create_table(
        "ELAN_FILE_TO_MEDIA",
        sa.Column("elan_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["elan_id"], ["ELAN_FILE.elan_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["media_id"], ["ELAN_FILE_MEDIA.media_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("elan_id", "media_id"),
    )
    op.create_table(
        "TIER",
        sa.Column("tier_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tier_name", sa.String(), nullable=False),
        sa.Column("linguistic_type_ref", sa.String(length=255), nullable=False),
        sa.Column("eaf_attributes", sa.JSON(), nullable=False),
        sa.Column("elan_id", sa.Integer(), nullable=False),
        sa.Column("parent_tier_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["elan_id"], ["ELAN_FILE.elan_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_tier_id"], ["TIER.tier_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tier_id"),
        sa.UniqueConstraint("elan_id", "tier_name", name="uq_tier_elan_name"),
    )
    op.create_table(
        "TIER_GROUP",
        sa.Column("tier_group_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("elan_id", sa.Integer(), nullable=False),
        sa.Column("elan_file_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["elan_id"], ["ELAN_FILE.elan_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["PROJECT.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["TIER_SECTION.tier_section_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("tier_group_id"),
    )
    op.create_index(
        op.f("ix_TIER_GROUP_tier_group_id"),
        "TIER_GROUP",
        ["tier_group_id"],
        unique=False,
    )
    op.create_table(
        "ANNOTATION",
        sa.Column("annotation_id", sa.String(length=50), nullable=False),
        sa.Column("elan_id", sa.Integer(), nullable=False),
        sa.Column("value_id", sa.Integer(), nullable=False),
        sa.Column("annotation_kind", sa.String(length=16), nullable=False),
        sa.Column("annotation_ref", sa.String(length=50), nullable=True),
        sa.Column("previous_annotation", sa.String(length=50), nullable=True),
        sa.Column("cv_entry_ref", sa.String(length=255), nullable=True),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.Column("start_time", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("end_time", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["elan_id"], ["ELAN_FILE.elan_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["TIER.tier_id"],
        ),
        sa.ForeignKeyConstraint(
            ["value_id"], ["ANNOTATION_VALUE.value_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("annotation_id", "elan_id"),
    )
    op.create_table(
        "ELAN_FILE_TO_TIER",
        sa.Column("elan_id", sa.Integer(), nullable=False),
        sa.Column("tier_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["elan_id"],
            ["ELAN_FILE.elan_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tier_id"],
            ["TIER.tier_id"],
        ),
        sa.PrimaryKeyConstraint("elan_id", "tier_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this database revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ELAN_FILE_TO_TIER")
    op.drop_table("ANNOTATION")
    op.drop_index(op.f("ix_TIER_GROUP_tier_group_id"), table_name="TIER_GROUP")
    op.drop_table("TIER_GROUP")
    op.drop_table("TIER")
    op.drop_table("ELAN_FILE_TO_MEDIA")
    op.drop_table("EAF_REVISION")
    op.drop_table("CONFLICT_OF_ELAN_FILE")
    op.drop_table("COMMENT_ELAN_FILE")
    op.drop_table("ELAN_FILE")
    op.drop_table("COMMENT_PROJECT")
    op.drop_table("COMMENT_CONFLICT")
    op.drop_table("USER_WORK_ON_CONFLICT")
    op.drop_table("USER_TO_PROJECT")
    op.drop_table("STANDARD_COMPONENT")
    op.drop_table("PENDING_UPLOAD")
    op.drop_index(
        op.f("ix_NOTIFICATION_PREFERENCE_user_id"), table_name="NOTIFICATION_PREFERENCE"
    )
    op.drop_table("NOTIFICATION_PREFERENCE")
    op.drop_index(op.f("ix_NOTIFICATION_user_id"), table_name="NOTIFICATION")
    op.drop_index(op.f("ix_NOTIFICATION_is_read"), table_name="NOTIFICATION")
    op.drop_index(op.f("ix_NOTIFICATION_created_at"), table_name="NOTIFICATION")
    op.drop_table("NOTIFICATION")
    op.drop_table("INVITATION")
    op.drop_table("FILE_CONTENT")
    op.drop_table("EFFECTIVE_NAMING_STANDARD")
    op.drop_table("COMMENT")
    op.drop_index(op.f("ix_AUDIT_EVENT_occurred_at"), table_name="AUDIT_EVENT")
    op.drop_index(op.f("ix_AUDIT_EVENT_action"), table_name="AUDIT_EVENT")
    op.drop_table("AUDIT_EVENT")
    op.drop_index(op.f("ix_USER_username"), table_name="USER")
    op.drop_index(op.f("ix_USER_role"), table_name="USER")
    op.drop_index(op.f("ix_USER_last_login"), table_name="USER")
    op.drop_index(op.f("ix_USER_is_verified_account"), table_name="USER")
    op.drop_index(op.f("ix_USER_is_active"), table_name="USER")
    op.drop_index(op.f("ix_USER_instance_id"), table_name="USER")
    op.drop_index(op.f("ix_USER_email"), table_name="USER")
    op.drop_index(op.f("ix_USER_department"), table_name="USER")
    op.drop_index(op.f("ix_USER_affiliation"), table_name="USER")
    op.drop_index(op.f("ix_USER_address_id"), table_name="USER")
    op.drop_table("USER")
    op.drop_table("PROJECT_NAMING_STANDARD")
    op.drop_table("PROJECT_LOCATION_FILE_TYPE")
    op.drop_index(op.f("ix_TIER_SECTION_tier_section_id"), table_name="TIER_SECTION")
    op.drop_table("TIER_SECTION")
    op.drop_table("PROJECT_FILE_TYPE")
    op.drop_table("PROJECT_ANNOT_STANDARD")
    op.drop_table("COMPONENT_ACCEPTED_VALUE")
    op.drop_index(op.f("ix_ADDRESS_postal_code"), table_name="ADDRESS")
    op.drop_index(op.f("ix_ADDRESS_city_id"), table_name="ADDRESS")
    op.drop_table("ADDRESS")
    op.drop_index(op.f("ix_PROJECT_deleted_at"), table_name="PROJECT")
    op.drop_table("PROJECT")
    op.drop_table("COMPONENT_TEMPLATE")
    op.drop_index(op.f("ix_CITY_city_name"), table_name="CITY")
    op.drop_index("idx_country_city", table_name="CITY")
    op.drop_table("CITY")
    op.drop_index(op.f("ix_OUTBOX_EVENT_aggregate_id"), table_name="OUTBOX_EVENT")
    op.drop_table("OUTBOX_EVENT")
    op.drop_table("INSTANCE")
    op.drop_table("FILE_TYPE")
    op.drop_table("ELAN_FILE_MEDIA")
    op.drop_index(op.f("ix_COUNTRY_country_name"), table_name="COUNTRY")
    op.drop_index(op.f("ix_COUNTRY_country_code"), table_name="COUNTRY")
    op.drop_table("COUNTRY")
    op.drop_table("CONFLICT")
    op.drop_table("ANNOTATION_VALUE")
    op.drop_table("ANNOTATION_STANDARD")
    op.drop_table("ACCEPTED_VALUE")
    # PostgreSQL enum types are schema objects and outlive the tables that use
    # them. Remove the types owned by this initial revision so a full
    # downgrade followed by an upgrade is reproducible.
    for enum_name in (
        "commenttargettype",
        "invitationstatus",
        "severity",
        "status",
        "type",
        "userrole",
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))
    # ### end Alembic commands ###
