"""Generating this installation's secrets once, during guided setup.

An institution installs ELANORA itself. Asking whoever runs the installer to
invent a signing key, an encryption key and a backup passphrase produces weak
secrets, or blank ones. The installation generates them instead, writes them
where the composition already reads its configuration, and keeps whatever is
already there.

Nothing here rotates an existing secret. Re-running setup must be safe, and a
changed backup passphrase would make every backup taken so far unreadable.
"""

import os
import secrets
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from cryptography.fernet import Fernet

# Long enough for the production configuration check, which refuses short keys.
SIGNING_KEY_BYTES = 32
PASSPHRASE_BYTES = 32
OWNER_ONLY = 0o600


def _fernet_key() -> str:
    return Fernet.generate_key().decode("ascii")


MANAGED_SECRETS: dict[str, Callable[[], str]] = {
    # Signs access and refresh tokens.
    "JWT_SECRET_KEY": lambda: secrets.token_hex(SIGNING_KEY_BYTES),
    # Authorizes the one-time institution bootstrap.
    "SETUP_TOKEN": lambda: secrets.token_urlsafe(SIGNING_KEY_BYTES),
    # The database this installation creates for itself.
    "DB_PASSWORD": lambda: secrets.token_urlsafe(SIGNING_KEY_BYTES),
    # Encrypts queued verification and password-reset messages.
    "OUTBOX_ENCRYPTION_KEYS": _fernet_key,
    # Encrypts the installation's own backups. Never regenerate: old backups
    # would stop opening.
    "ELANORA_BACKUP_PASSPHRASE": lambda: secrets.token_urlsafe(PASSPHRASE_BYTES),
}


@dataclass
class ProvisioningReport:
    """Which secrets were created and which were left as they were.

    Deliberately carries names only: the installer prints this.
    """

    path: str
    generated: list[str] = field(default_factory=list)
    kept: list[str] = field(default_factory=list)


def read_env_file(path: Path) -> dict[str, str]:
    """Read a ``KEY=value`` file, ignoring comments and blank lines."""
    if not path.exists():
        return {}
    values = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def provision_secrets(path: Path) -> ProvisioningReport:
    """Fill in any secret this installation needs but does not yet have."""
    existing = read_env_file(path)
    report = ProvisioningReport(path=str(path))
    additions = {}
    for name, generate in MANAGED_SECRETS.items():
        if existing.get(name):
            report.kept.append(name)
            continue
        additions[name] = generate()
        report.generated.append(name)

    if additions:
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# Generated by ELANORA setup. Keep this file; do not share it.")
        lines.extend(f"{name}={value}" for name, value in additions.items())
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    # Applies whether or not anything was added: an existing file may be loose.
    os.chmod(path, OWNER_ONLY)
    return report
